name: Staging (Development) CI/CD

on:
  push:
  pull_request:
    branches:
      - develop

jobs:
  test:
    if: ${{ github.repository == 'BuildForSDGCohort2/whatz-hot-frontend' }}
    name: Linting and Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node and Install Packages
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Run Linting and Tests
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          npm ci
          npm run lint
          npm run build
          npm run test:codacy

  deploy:
    if: ${{ github.event_name == 'push' && github.repository == 'BuildForSDGCohort2/whatz-hot-frontend' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build'
          production-branch: develop
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
